INSERT INTO uncertainTable VALUES(258,'Sales');
INSERT INTO uncertainTable VALUES(223,'Finance');
INSERT INTO uncertainTable VALUES(14,'Operations');
INSERT INTO uncertainTable VALUES(463,'Human Resources');
INSERT INTO uncertainTable VALUES(286,'Research and Development');
INSERT INTO uncertainTable VALUES(495,'Management');
INSERT INTO uncertainTable VALUES(382,'Human Resources');
INSERT INTO uncertainTable VALUES(189,'Operations');
INSERT INTO uncertainTable VALUES(238,'Sales');
INSERT INTO uncertainTable VALUES(239,'Research and Development');
INSERT INTO uncertainTable VALUES(354,'Human Resources');
INSERT INTO uncertainTable VALUES(163,'Sales');
INSERT INTO uncertainTable VALUES(123,'Sales');
INSERT INTO uncertainTable VALUES(60,'IT');
INSERT INTO uncertainTable VALUES(436,'Human Resources');
INSERT INTO uncertainTable VALUES(14,'IT');
INSERT INTO uncertainTable VALUES(412,'Finance');
INSERT INTO uncertainTable VALUES(53,'IT');
INSERT INTO uncertainTable VALUES(357,'Sales');
INSERT INTO uncertainTable VALUES(339,'IT');
INSERT INTO uncertainTable VALUES(225,'Finance');
INSERT INTO uncertainTable VALUES(372,'Accounting');
INSERT INTO uncertainTable VALUES(253,'Sales');
INSERT INTO uncertainTable VALUES(64,'Operations');
INSERT INTO uncertainTable VALUES(340,'IT');
INSERT INTO uncertainTable VALUES(111,'Finance');
INSERT INTO uncertainTable VALUES(321,'IT');
INSERT INTO uncertainTable VALUES(473,'IT');
INSERT INTO uncertainTable VALUES(388,'IT');
INSERT INTO uncertainTable VALUES(358,'Human Resources');
INSERT INTO uncertainTable VALUES(224,'Human Resources');
INSERT INTO uncertainTable VALUES(196,'Management');
INSERT INTO uncertainTable VALUES(389,'Management');
INSERT INTO uncertainTable VALUES(255,'Sales');
INSERT INTO uncertainTable VALUES(47,'Sales');
INSERT INTO uncertainTable VALUES(397,'IT');
INSERT INTO uncertainTable VALUES(44,'Research and Development');
INSERT INTO uncertainTable VALUES(183,'Sales');
INSERT INTO uncertainTable VALUES(265,'Research and Development');
INSERT INTO uncertainTable VALUES(129,'Accounting');
INSERT INTO uncertainTable VALUES(300,'Operations');
INSERT INTO uncertainTable VALUES(494,'Human Resources');
INSERT INTO uncertainTable VALUES(2,'Purchasing');
INSERT INTO uncertainTable VALUES(4,'Human Resources');
INSERT INTO uncertainTable VALUES(14,'Accounting');
INSERT INTO uncertainTable VALUES(432,'Purchasing');
INSERT INTO uncertainTable VALUES(35,'Management');
INSERT INTO uncertainTable VALUES(111,'Marketing');
INSERT INTO uncertainTable VALUES(274,'Accounting');
INSERT INTO uncertainTable VALUES(355,'Marketing');

