INSERT INTO uncertainTable VALUES(116,'Management');
INSERT INTO uncertainTable VALUES(300,'Operations');
INSERT INTO uncertainTable VALUES(152,'Research and Development');
INSERT INTO uncertainTable VALUES(196,'Human Resources');
INSERT INTO uncertainTable VALUES(197,'Accounting');
INSERT INTO uncertainTable VALUES(232,'Operations');
INSERT INTO uncertainTable VALUES(34,'Finance');
INSERT INTO uncertainTable VALUES(420,'Finance');
INSERT INTO uncertainTable VALUES(406,'Research and Development');
INSERT INTO uncertainTable VALUES(457,'IT');
INSERT INTO uncertainTable VALUES(431,'Marketing');
INSERT INTO uncertainTable VALUES(273,'Accounting');
INSERT INTO uncertainTable VALUES(438,'Purchasing');
INSERT INTO uncertainTable VALUES(179,'IT');
INSERT INTO uncertainTable VALUES(16,'Accounting');
INSERT INTO uncertainTable VALUES(409,'Research and Development');
INSERT INTO uncertainTable VALUES(131,'Sales');
INSERT INTO uncertainTable VALUES(143,'Finance');
INSERT INTO uncertainTable VALUES(91,'Research and Development');
INSERT INTO uncertainTable VALUES(463,'Marketing');
INSERT INTO uncertainTable VALUES(420,'IT');
INSERT INTO uncertainTable VALUES(284,'Operations');
INSERT INTO uncertainTable VALUES(365,'Sales');
INSERT INTO uncertainTable VALUES(164,'IT');
INSERT INTO uncertainTable VALUES(216,'IT');
INSERT INTO uncertainTable VALUES(135,'Operations');
INSERT INTO uncertainTable VALUES(270,'Sales');
INSERT INTO uncertainTable VALUES(291,'Management');
INSERT INTO uncertainTable VALUES(116,'Marketing');
INSERT INTO uncertainTable VALUES(337,'Human Resources');
INSERT INTO uncertainTable VALUES(237,'Sales');
INSERT INTO uncertainTable VALUES(96,'Finance');
INSERT INTO uncertainTable VALUES(297,'IT');
INSERT INTO uncertainTable VALUES(133,'Management');
INSERT INTO uncertainTable VALUES(311,'Research and Development');
INSERT INTO uncertainTable VALUES(364,'Purchasing');
INSERT INTO uncertainTable VALUES(464,'Sales');
INSERT INTO uncertainTable VALUES(386,'Human Resources');
INSERT INTO uncertainTable VALUES(314,'Purchasing');
INSERT INTO uncertainTable VALUES(372,'Marketing');
INSERT INTO uncertainTable VALUES(375,'Sales');
INSERT INTO uncertainTable VALUES(120,'Management');
INSERT INTO uncertainTable VALUES(103,'Management');
INSERT INTO uncertainTable VALUES(149,'Accounting');
INSERT INTO uncertainTable VALUES(59,'Research and Development');
INSERT INTO uncertainTable VALUES(371,'Purchasing');
INSERT INTO uncertainTable VALUES(66,'Sales');
INSERT INTO uncertainTable VALUES(352,'Marketing');
INSERT INTO uncertainTable VALUES(210,'IT');
INSERT INTO uncertainTable VALUES(461,'Marketing');

