INSERT INTO uncertainTable VALUES(54,'IT');
INSERT INTO uncertainTable VALUES(306,'Sales');
INSERT INTO uncertainTable VALUES(99,'Marketing');
INSERT INTO uncertainTable VALUES(350,'Accounting');
INSERT INTO uncertainTable VALUES(186,'Purchasing');
INSERT INTO uncertainTable VALUES(499,'IT');
INSERT INTO uncertainTable VALUES(266,'Purchasing');
INSERT INTO uncertainTable VALUES(136,'Research and Development');
INSERT INTO uncertainTable VALUES(432,'Research and Development');
INSERT INTO uncertainTable VALUES(308,'IT');
INSERT INTO uncertainTable VALUES(430,'Management');
INSERT INTO uncertainTable VALUES(316,'Purchasing');
INSERT INTO uncertainTable VALUES(27,'Purchasing');
INSERT INTO uncertainTable VALUES(6,'Sales');
INSERT INTO uncertainTable VALUES(288,'IT');
INSERT INTO uncertainTable VALUES(460,'Operations');
INSERT INTO uncertainTable VALUES(479,'Accounting');
INSERT INTO uncertainTable VALUES(308,'Management');
INSERT INTO uncertainTable VALUES(435,'Human Resources');
INSERT INTO uncertainTable VALUES(127,'Accounting');
INSERT INTO uncertainTable VALUES(193,'Human Resources');
INSERT INTO uncertainTable VALUES(76,'Sales');
INSERT INTO uncertainTable VALUES(129,'Human Resources');
INSERT INTO uncertainTable VALUES(335,'Sales');
INSERT INTO uncertainTable VALUES(377,'Management');
INSERT INTO uncertainTable VALUES(413,'Finance');
INSERT INTO uncertainTable VALUES(293,'Sales');
INSERT INTO uncertainTable VALUES(84,'Human Resources');
INSERT INTO uncertainTable VALUES(394,'Operations');
INSERT INTO uncertainTable VALUES(348,'Marketing');
INSERT INTO uncertainTable VALUES(43,'Finance');
INSERT INTO uncertainTable VALUES(423,'Sales');
INSERT INTO uncertainTable VALUES(81,'Accounting');
INSERT INTO uncertainTable VALUES(336,'Marketing');
INSERT INTO uncertainTable VALUES(237,'Finance');
INSERT INTO uncertainTable VALUES(474,'Operations');
INSERT INTO uncertainTable VALUES(281,'Marketing');
INSERT INTO uncertainTable VALUES(148,'IT');
INSERT INTO uncertainTable VALUES(75,'Research and Development');
INSERT INTO uncertainTable VALUES(378,'Sales');
INSERT INTO uncertainTable VALUES(178,'Human Resources');
INSERT INTO uncertainTable VALUES(7,'Human Resources');
INSERT INTO uncertainTable VALUES(420,'Finance');
INSERT INTO uncertainTable VALUES(465,'Marketing');
INSERT INTO uncertainTable VALUES(121,'Management');
INSERT INTO uncertainTable VALUES(281,'Human Resources');
INSERT INTO uncertainTable VALUES(283,'Purchasing');
INSERT INTO uncertainTable VALUES(177,'Accounting');
INSERT INTO uncertainTable VALUES(188,'Accounting');
INSERT INTO uncertainTable VALUES(296,'Sales');